name: Stride
options:
  bundleIdPrefix: com.stride
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: Stride
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    PRODUCT_BUNDLE_IDENTIFIER: com.stride.stride

targets:
  Stride:
    type: application
    platform: iOS
    sources:
      - path: Stride
    resources:
      - path: Stride/Resources
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
  StrideTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: StrideTests
    dependencies:
      - target: Stride
